name: Upload Website to S3

on:
  push:
    branches: [main]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate HTML/CSS/JS files
        run: |
          mkdir -p dist
          echo "<html><body>Hello World</body></html>" > dist/index.html
          echo "body { background: #f5f5f5; }" > dist/style.css

      - name: Upload to S3
        uses: aws-actions/s3-sync@v1
        with:
          bucket: private-bucket-s3-access
          source-dir: dist
          destination-dir: files/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
